languageCode = "en"
languageName = "English"
weight = 1

title = "El Sentimiento de un Latino"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false

  dateFormat = "2 January 2006"

  #mainSections = ["section1", "section2"]
  #description = "Este es el blog que un europeo lee pero no entiende, el blog de un latino en Europa"

[author]
  name = "Kevin León"
  image = "img/author.jpg"
  headline = "Un latino en Europa"
  bio = "Photography, music, coffee, collecting, etc."
  links = [
     { instagram = "https://instagram.com/kevinleonj" },
     { linkedin = "https://linkedin.com/in/kevinleonj" },
     { spotify = "https://open.spotify.com/intl-es/track/6nSLh6LLFcvfMAz83AgbbK?si=0a631384c6c44dd8" },
   ]
